/* Convex C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef CONVEX_FFI_H
#define CONVEX_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque object handle. `0` is reserved as INVALID.
 */
typedef uint64_t Handle;

/**
 * Sentinel for "no handle".
 */
#define INVALID_HANDLE 0

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a string returned by any FFI function in this crate.
 */
void convex_string_free(char *s);

/**
 * Get the last error message set by a stateful constructor.
 *
 * The returned pointer is valid until the next call into this library on
 * the same thread; do not free it.
 */
const char *convex_last_error(void);

/**
 * Clear the thread-local last-error slot.
 */
void convex_clear_error(void);

/**
 * Library version (`CARGO_PKG_VERSION`). Static; do not free.
 */
const char *convex_version(void);

/**
 * Build a bond from a `BondSpec` JSON. Returns `0` on failure.
 */
Handle convex_bond_from_json(const char *spec_json);

/**
 * Build a curve from a `CurveSpec` JSON. Returns `0` on failure.
 */
Handle convex_curve_from_json(const char *spec_json);

/**
 * Returns a JSON description of the registered object.
 *
 * Free the returned pointer with [`convex_string_free`].
 */
char *convex_describe(Handle handle);

/**
 * Releases an object by handle. No-op on invalid handle.
 */
void convex_release(Handle handle);

/**
 * Number of registered objects.
 */
int32_t convex_object_count(void);

/**
 * Returns a JSON array of `{handle,kind,name?}` entries for every registered
 * object. Caller frees with [`convex_string_free`].
 */
char *convex_list_objects(void);

/**
 * Clears all registered objects.
 */
void convex_clear_all(void);

/**
 * Price a bond. Request: `PricingRequest`. Response: `PricingResponse`.
 */
char *convex_price(const char *request_json);

/**
 * Risk metrics. Request: `RiskRequest`. Response: `RiskResponse`.
 */
char *convex_risk(const char *request_json);

/**
 * Spread (Z/G/I/ASW/OAS/DM dispatch). Request: `SpreadRequest`. Response:
 * `SpreadResponse`.
 */
char *convex_spread(const char *request_json);

/**
 * Bond cashflow schedule. Request: `CashflowRequest`. Response: `CashflowResponse`.
 */
char *convex_cashflows(const char *request_json);

/**
 * Curve point query. Request: `CurveQueryRequest`. Response: `CurveQueryResponse`.
 */
char *convex_curve_query(const char *request_json);

/**
 * Make-whole call price. Request: `MakeWholeRequest`. Response: `MakeWholeResponse`.
 *
 * Computes the make-whole call redemption price at a future call date for
 * a callable bond carrying a make-whole spread. Discount uses the bond's
 * own day count and frequency; treasury rate is supplied by the caller.
 */
char *convex_make_whole(const char *request_json);

/**
 * Build a position risk profile. Request: `RiskProfileRequest`. Response:
 * `RiskProfile` (modified/Macaulay duration, convexity, DV01, key-rate
 * buckets, market value, provenance). The profile round-trips back into
 * [`convex_hedge`] and [`convex_compare`].
 */
char *convex_risk_profile(const char *request_json);

/**
 * Propose a hedge for a position profile. Request: `HedgeRequest` (carries a
 * `strategy` tag + the `RiskProfile` from [`convex_risk_profile`]). Response:
 * `HedgeProposal` (trades, residual risk, cost bps, tradeoff notes).
 */
char *convex_hedge(const char *request_json);

/**
 * Compare hedge proposals against a position. Request: `CompareRequest`.
 * Response: `CompareResponse` (`ComparisonReport` + optional narrative).
 */
char *convex_compare(const char *request_json);

/**
 * Returns the JSON schema for a named DTO type, or an error envelope.
 *
 * Type names: `Mark`, `BondSpec`, `CurveSpec`, `PricingRequest`,
 * `PricingResponse`, `RiskRequest`, `RiskResponse`, `SpreadRequest`,
 * `SpreadResponse`, `CashflowRequest`, `CashflowResponse`,
 * `CurveQueryRequest`, `CurveQueryResponse`.
 */
char *convex_schema(const char *type_name);

/**
 * Parse a textual mark (e.g. `"99.5C"`, `"4.65%"`, `"+125bps@USD.SOFR"`).
 *
 * Returns a JSON envelope; on success, `result` is the canonical `Mark` JSON.
 */
char *convex_mark_parse(const char *text);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CONVEX_FFI_H */
